---
output:
  html_document: default
  pdf_document: default
---

This notebook investigates the data loss from enforcing that the nr. of tests in a given geographical units does not exceed the number of kids.

```{r, message=FALSE, warning=FALSE}
source("../../init.R")
source("load_and_preprocess.R")
library(tidyverse)
```

Load a state and inspect tested/kids ratio.

```{r}
plot_tests_p_kid_tract <- function(state_abbr) {
  oh_merged <- single_state_tract(state_abbr, drop_if_multiple_testing_bool = FALSE)
  
  # Calculate total number and proportion of cases with tests_p_kid > 1
  total_cases <- sum(oh_merged$tests_p_kid > 1, na.rm = TRUE)
  proportion_cases <- total_cases / nrow(oh_merged)
  
  # Plot tests_p_kid for values above 1 and add total number and proportion of cases in title
  oh_merged |> 
    filter(tests_p_kid > 1) |>
    ggplot(aes(x = tests_p_kid)) +
    geom_histogram() +
    ggtitle(paste(state_abbr, " - Total cases: ", total_cases, " (", round(proportion_cases * 100, 2), "%)", sep = ""))
}

```

Iterate for all tract states:

```{r, cache = TRUE}
for (state_abbr in tract_states) {
  p <- plot_tests_p_kid_tract(state_abbr)
  print(p)
}
```

Same for ZIP states:

```{r}
plot_tests_p_kid_zip <- function(state_abbr) {
  oh_merged <- single_state_zip(state_abbr, drop_if_multiple_testing_bool = FALSE)
  
  # Calculate total number and proportion of cases with tests_p_kid > 1
  total_cases <- sum(oh_merged$tests_p_kid > 1, na.rm = TRUE)
  proportion_cases <- total_cases / nrow(oh_merged)
  
  # Plot tests_p_kid for values above 1 and add total number and proportion of cases in title
  oh_merged |> 
    filter(tests_p_kid > 1) |>
    ggplot(aes(x = tests_p_kid)) +
    geom_histogram() +
    ggtitle(paste(state_abbr, " - Total cases: ", total_cases, " (", round(proportion_cases * 100, 2), "%)", sep = ""))
}
```

Iterate for all ZIP states:

```{r, cache = TRUE}
for (state_abbr in zip_states) {
  tryCatch({
    p <- plot_tests_p_kid_zip(state_abbr)
    print(p)
  }, error = function(e) {
    message(paste("Error processing state:", state_abbr))
  })
}
```

add summary table by year for ZIP?