---
title: "Descriptives of tract states"
format:
  pdf:
    toc: true
    code-fold: true
---

```{r, message=FALSE, warning=FALSE}
library(kableExtra)
library(tidyverse)
library(jsonlite)
source("../../init.R")
source("load_and_preprocess.R")
```

Getting metadata
```{r, error=TRUE}
# get metadata from ~US root
metadata  <- fromJSON("../metadata.json")
# extract required metadata (lists)
zip_states <- metadata$zip_states
tract_states <- metadata$tract_states
```

```{r, error=TRUE}
source("compute_descriptives.R")
```

# TRACT states

```{r, error=TRUE}
print(tract_states)
```

## Ohio

```{r, error=TRUE}
oh_summary <- data_summary("OH", year = NULL)
```

```{r, error=TRUE}
oh_summary[[1]] |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
oh_summary[[2]] 
```

```{r, error=TRUE}
oh_summary[[3]]
```

```{r, error=TRUE}
oh_summary[[4]]
```

```{r, error=TRUE}
oh_lead_model <- lead_count_model_summary("OH", year = 2010)
```

```{r, error=TRUE}
oh_lead_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
oh_lead_model$plot
```

```{r, error=TRUE}
oh_test_model <- test_count_model_summary("OH", year = 2012)
```

```{r, error=TRUE}
oh_test_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
oh_test_model$plot
```

## Pennsylvania

```{r, error=TRUE}
pa_summary <- data_summary("PA", year = NULL)
```

```{r, error=TRUE}
pa_summary[[1]] |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
pa_summary[[2]] 
```

```{r, error=TRUE}
pa_summary[[3]]
```

```{r, error=TRUE}
pa_summary[[4]]
```

```{r, error=TRUE}
pa_lead_model <- lead_count_model_summary("PA", year = 2007)
```

```{r, error=TRUE}
pa_lead_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
pa_lead_model$plot
```

```{r, error=TRUE}
pa_test_model <- test_count_model_summary("PA", year = 2007)
```

```{r, error=TRUE}
pa_test_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
pa_test_model$plot
```

## Colorado

```{r, error=TRUE}
co_summary <- data_summary("CO", year = NULL)
```

```{r, error=TRUE}
co_summary[[1]] |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
co_summary[[2]] 
```

```{r, error=TRUE}
co_summary[[3]]
```

```{r, error=TRUE}
co_summary[[4]]
```

```{r, error=TRUE}
co_lead_model <- lead_count_model_summary("CO", year = 2014)
```

```{r, error=TRUE}
co_lead_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
co_lead_model$plot
```

```{r, error=TRUE}
co_test_model <- test_count_model_summary("CO", year = 2014)
```

```{r, error=TRUE}
co_test_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
co_test_model$plot
```

## Maryland

```{r, error=TRUE}
md_summary <- data_summary("MD", year = NULL)
```

```{r, error=TRUE}
md_summary[[1]] |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
md_summary[[2]] 
```

```{r, error=TRUE}
md_summary[[3]]
```

```{r, error=TRUE}
md_summary[[4]]
```

```{r, error=TRUE}
md_lead_model <- lead_count_model_summary("MD", year = 2011)
```

```{r, error=TRUE}
md_lead_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
md_lead_model$plot
```

```{r, error=TRUE}
md_test_model <- test_count_model_summary("MD", year = 2011)
```

```{r, error=TRUE}
md_test_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
md_test_model$plot
```

## Massachusetts

```{r, error=TRUE}
ma_summary <- data_summary("MA", year = NULL)
```

```{r, error=TRUE}
ma_summary[[1]] |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
ma_summary[[2]] 
```

```{r, error=TRUE}
ma_summary[[3]]
```

```{r, error=TRUE}
ma_summary[[4]]
```

```{r, error=TRUE}
ma_lead_model <- lead_count_model_summary("MA", year = 2014)
```

```{r, error=TRUE}
ma_lead_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
ma_lead_model$plot
```

```{r, error=TRUE}
ma_test_model <- test_count_model_summary("MA", year = 2014)
```

```{r, error=TRUE}
ma_test_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
ma_test_model$plot
```

## Minnesota

```{r, error=TRUE}
mn_summary <- data_summary("MN", year = NULL)
```

```{r, error=TRUE}
mn_summary[[1]] |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
mn_summary[[2]] 
```

```{r, error=TRUE}
mn_summary[[3]]
```

```{r, error=TRUE}
mn_summary[[4]]
```

```{r, error=TRUE}
mn_lead_model <- lead_count_model_summary("MN", year = 2014)
```

```{r, error=TRUE}
mn_lead_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
mn_lead_model$plot
```

```{r, error=TRUE}
mn_test_model <- test_count_model_summary("MN", year = 2014)
```

```{r, error=TRUE}
mn_test_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
mn_test_model$plot
```

NYC is not available.

## North Carolina

```{r, error=TRUE}
nc_summary <- data_summary("NC", year = NULL)
```

```{r, error=TRUE}
nc_summary[[1]] |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
nc_summary[[2]] 
```

```{r, error=TRUE}
nc_summary[[3]]
```

```{r, error=TRUE}
nc_summary[[4]]
```

```{r, error=TRUE}
nc_lead_model <- lead_count_model_summary("NC", year = 2014)
```

```{r, error=TRUE}
nc_lead_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
nc_lead_model$plot
```

```{r, error=TRUE}
nc_test_model <- test_count_model_summary("NC", year = 2014)
```

```{r, error=TRUE}
nc_test_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
nc_test_model$plot
```

## Indiana

```{r, error=TRUE}
in_summary <- data_summary("IN", year = NULL)
```

```{r, error=TRUE}
in_summary[[1]] |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
in_summary[[2]] 
```

```{r, error=TRUE}
in_summary[[3]]
```

```{r, error=TRUE}
in_summary[[4]]
```

```{r, error=TRUE}
in_lead_model <- lead_count_model_summary("IN", year = 2013)
```

```{r, error=TRUE}
in_lead_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
in_lead_model$plot
```

```{r, error=TRUE}
in_test_model <- test_count_model_summary("IN", year = 2013)
```

```{r, error=TRUE}
in_test_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
in_test_model$plot
```

## Oregon

```{r, error=TRUE}
or_summary <- data_summary("OR", year = NULL)
```

```{r, error=TRUE}
or_summary[[1]] |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
or_summary[[2]] 
```

```{r, error=TRUE}
or_summary[[3]]
```

```{r, error=TRUE}
or_summary[[4]]
```

```{r, error=TRUE}
or_lead_model <- lead_count_model_summary("OR", year = 2010)
```

```{r, error=TRUE}
or_lead_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
or_lead_model$plot
```

```{r, error=TRUE}
or_test_model <- test_count_model_summary("OR", year = 2010)
```

```{r, error=TRUE}
or_test_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
or_test_model$plot
```

## New Hampshire

```{r, error=TRUE}
nh_summary <- data_summary("NH", year = NULL)
```

```{r, error=TRUE}
nh_summary[[1]] |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
nh_summary[[2]] 
```

```{r, error=TRUE}
nh_summary[[3]]
```

```{r, error=TRUE}
nh_summary[[4]]
```

```{r, error=TRUE}
nh_lead_model <- lead_count_model_summary("NH", year = 2010)
```

```{r, error=TRUE}
nh_lead_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
nh_lead_model$plot
```

```{r, error=TRUE}
nh_test_model <- test_count_model_summary("NH", year = 2010)
```

```{r, error=TRUE}
nh_test_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
nh_test_model$plot
```

## Wisconsin

```{r, error=TRUE}
wi_summary <- data_summary("WI", year = NULL)
```

```{r, error=TRUE}
wi_summary[[1]] |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
wi_summary[[2]] 
```

```{r, error=TRUE}
wi_summary[[3]]
```

```{r, error=TRUE}
wi_summary[[4]]
```

```{r, error=TRUE}
wi_lead_model <- lead_count_model_summary("WI", year = 2007)
```

```{r, error=TRUE}
wi_lead_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
wi_lead_model$plot
```

```{r, error=TRUE}
wi_test_model <- test_count_model_summary("WI", year = 2007)
```

```{r, error=TRUE}
wi_test_model$table |> knitr::kable() |> kable_styling(latex_options = "scale_down")
```

```{r, error=TRUE}
wi_test_model$plot
```

